### ISSUE TITLE
Merging vertices by distance causes a memory leak

### ISSUE THREAD

**Issue by Stroopwafe1** [Blender-PLY-Project/blender#111]
I don't have the time or energy to fix this right now at 11 pm. But this should be fixed.
Essentially, you are assigning a new pointer to the old pointer, meaning the old data is no longer referenced and is a memory leak.
When we merge by distance, we should free the old mesh.
`mesh = blender::geometry::mesh_merge_by_distance_all(*mesh, IndexMask(mesh->totvert), 0.0001f).value();`

**Comment by Kwonunn** [comment]
Sigh.........

I'll fix it

**Comment by Kwonunn** [comment]
Ok, this is sadly not as easy as it seems. 

Simply doing this:
```
if (params.merge_verts) {
    Mesh *new_mesh = blender::geometry::mesh_merge_by_distance_all(*mesh, IndexMask(mesh->totvert), 0.0001f)
               .value();
    BKE_id_free(nullptr, mesh);
    mesh = new_mesh;
  }
```
causes a problem because BKE_id_free won't free the mesh without the bmain if the mesh was created specifically on the bmain. Since this is the case (`Mesh *mesh = BKE_mesh_add(bmain, ob_name);`) we'd need to do a bunch of parameter drilling which will break all the tests and is very ugly.

If there's a way to update the existing mesh when merging instead of replacing and having to free the original that would be ideal, I'll take a look into that first.
